[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
stream = "B3kcoBKPkVwVo3oUQ3bwndM3QgnEgfHXWu7ZbXxF3zaE"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
